title: Carter Luellen
tagline: B.S. Astrobiology
description: Chemical | Biological Research & Development
show_downloads: true

accent_image: /assets/IMG_1993.jpeg

defaults:
  -
    scope:
      path: ""
    values:
      image: '/assets/IMG_1995.jpg'

author:
  social:
    download: "Administrative Communicative Standards at the Florida Institute of Technology.docx.pdf"

remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

kramdown:
  hard_wrap: true





