title: Carter Luellen
tagline: "B.S. Astrobiology - Chemistry"
description: "Chemical | Biological Research & Development"
layout: welcome
title:  Welcome
cover:  true
menu:
  - title: About
    url:   /about/
  - title: Research
    url:   /research/
  - title: Contact
    url:   /contact/

layout: about
title:  About Me
---

Carter Luellen

baseurl: "/Luellen"

remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-include-cache

show_downloads: true
invert_sidebar: true

hydejack:
  no_inline_css: false

accent_image: /Luellen/assets/IMG_1995.jpeg




